### ISSUE TITLE
Add support for /msg shortcut

### ISSUE THREAD

**Issue by alanmoo** [mozilla/mattermoz#1]
In the message bar, typing `/msg` or `/dm` should allow the user to send a direct message to a user. Ideally it would populate a list of possible matches after the command has been matched

**Comment by floatingatoll** [comment]
Most IRC clients include default aliases for `/m` (to `/msg`) and `/q` (to `/query`), which may be of interest as well.

**Comment by alanmoo** [comment]
There doesn't seem to be an obvious way to map multiple aliases to the same command, but the pop-up list of commands is pretty useful, so I'd say let's see how people feel about this and then decide if another issue should be opened.

**Comment by alanmoo** [comment]
Submitted to Mattermost upstream as https://github.com/mattermost/platform/pull/2320

**Comment by alanmoo** [comment]
Landed upstream.
