### ISSUE TITLE
Should we set up the IRC server for IRC clients?

### ISSUE THREAD

**Issue by simonwex** [mozilla/mattermoz#25]

**Comment by simonwex** [comment]
Hey @cadecairos, could you investigate how much work this is?

**Comment by cadecairos** [comment]
The mattermost IRC bridge is a Go program that sadly, also uses a file based config.

I can fork my mattermost-heroku buildpack to work with the bridge. shouldn't be a massive undertaking.

@simonwex @alanmoo do this next milestone? I have about 1.5 hours left in my day and a few other things to take care of...

**Comment by alanmoo** [comment]
Makes sense to me, as we'll get a feel for what's needed starting next week.

**Comment by cadecairos** [comment]
moving to next milestone

**Comment by alanmoo** [comment]
@cadecairos is the above still valid? How much of an effort is this?

**Comment by cadecairos** [comment]
My guess is it's a day's work to make the buildpack.

**Comment by cadecairos** [comment]
It doesn't appear that people want/need this. closing!
