### ISSUE TITLE
Add support for embedded contextual content

### ISSUE THREAD

**Issue by alanmoo** [mozilla/mattermoz#3]
There are certain link types that generally point to small amounts of useful information that could reasonably be embedded in a chat log. Some examples that come to mind are
- gists
- pastebin
- direct links to images/gifs

Here's a preview of how it looks in IRCCloud, for reference

<img width="1051" alt="screenshot 2016-01-13 11 29 26" src="https://cloud.githubusercontent.com/assets/1682681/12305306/ec9baf98-b9e8-11e5-9af5-29b653e24574.png">

**Comment by alanmoo** [comment]
Image support appears to be in Mattermost 1.4

**Comment by cadecairos** [comment]
Gist embeds filed in #13

**Comment by alanmoo** [comment]
Pastebin may be moot since this supports multi-line messaging (with markdown preview). Closing for now, if Pastebin support is desired, an issue can be opened.
