### ISSUE TITLE
Disable ability to create new teams?

### ISSUE THREAD

**Issue by alanmoo** [mozilla/mattermoz#30]
It looks like if you hit [chat.mozillafoundation.org](http://chat.mozillafoundation.org), you can create a new team and you'll have no idea how to find the one everyone's on. As it is, I have a feeling there might be two in existence. @simonwex, should @cadecairos disable team creation so that only the link [chat.mozillafoundation.org/mozilla](http://chat.mozillafoundation.org/mozilla) works?

**Comment by cadecairos** [comment]
Team creation is currently enabled only for verified Mozilla foundation emails. 

Teams can also publicly list themselves at their own discretion.

We can disable it entirely too. 

Additionally, the admin console should let us see and manage all teams.

**Comment by simonwex** [comment]
Disabling it might make the most sense here until we see all the channels people make.

**Comment by cadecairos** [comment]
Team creation is now disabled
