### ISSUE TITLE
Update URL in verification emails

### ISSUE THREAD

**Issue by alanmoo** [mozilla/mattermoz#31]
The verification emails point to mattermoz-production.herokuapp.com, can we update that to the chat.mozillafoundation.org url?

**Comment by cadecairos** [comment]
Might have to rebuild it. I'll give that a shot next time I can.

**Comment by cadecairos** [comment]
the problem here was that cloudfront wasn't forwarding the host header (chat.mozillafoundation.org) to the heroku router. I've made that change but I think a different change I made to the buildpack might be causing emails to crash the server (lol) I'll back that out and rebuild to check

**Comment by cadecairos** [comment]
fixed
