### ISSUE TITLE
scrollbar in the browser?

### ISSUE THREAD

**Issue by Pomax** [mozilla/mattermoz#34]
There is no scrollbar visible in the browser, or anything else to indicate "where in the conversaion" you are. I don't know how far back scroll buffers go for mattermost, but I can see a lack of explicitly scrolling becoming a little iffy once chat takes off.

**Comment by cadecairos** [comment]
There's a scrollbar in my browser (FX nightly on Linux)

**Comment by Pomax** [comment]
No scrollbar in Chrome in Windows for me, assuming people use FF is probably a bad idea (if we want to do this to make moz more approachable for contributors at least =)

**Comment by alanmoo** [comment]
Looks like this is fixed in an upcoming release. https://mattermost.atlassian.net/browse/PLT-199
