### ISSUE TITLE
Links in email notifications go to wrong domain

### ISSUE THREAD

**Issue by simonwex** [mozilla/mattermoz#36]
When clicking on "go to channel" here: 
![image](https://cloud.githubusercontent.com/assets/25260/12936920/10001120-cf58-11e5-9634-e86b0cd34137.png)

It takes me to a link on the following domain:

`http://mattermoz-production.herokuapp.com/mozilla/...`

**Comment by alanmoo** [comment]
I believe this was a matter of the URL I was using to access the app.
