### ISSUE TITLE
Can we call it Mattermost?

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mattermoz#43]
Personally, I like the name Mattermoz. The things is... new staff and contributors are swamped with acronyms and confusing terms to learn. We could cut this orientation in half and remove 40% of the lingo: `Mattermoz` is our `instance` of `Mattermost`, an opensource alternative to `IRC` that's like `Slack`.

**Comment by Pomax** [comment]
this sounds like a thing that makes a lot of sense.

**Comment by alanmoo** [comment]
@simonwex and I were talking about changing it to "Mozilla Chat" (since the URL...)

**Comment by simonwex** [comment]
Renamed to https://github.com/mozilla/chat.mozillafoundation.org
