### ISSUE TITLE
UX - App Wrapper?

### ISSUE THREAD

**Issue by vazquez** [mozilla/mattermoz#48]
I've been talking to a few folks about Mattermoz. Most of the frustrations I hear are regarding the ecosystem that Mattermoz is living in (ie. a tab). It's hard for people to keep tabs on it (get it :stuck_out_tongue:)

I wonder, would it be possible (in the future) to create an wrapper so that Mattermoz acts as a desktop app?

**Comment by Pomax** [comment]
http://www.mattermost.org/community-applications/#native

added https://github.com/mozilla/mattermoz/issues/49 to discuss where to surface this persistently.

**Comment by alicoding** [comment]
https://github.com/alicoding/mattermoz-native/releases/tag/0.0.1
