### ISSUE TITLE
[onboarding] recommend app options

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/mattermoz#55]
"So many tabs!" might block adoption of Mattermost. Onboarding email/docs might include info on methods to run the web app like a native app (e.g. Fluid on OS X).

**Comment by Pomax** [comment]
there _are_ native apps for mattermost, we don't have to tell people how to pack it as webapp, we need to expose where the native app(s) can be downloaded.
1. http://www.mattermost.org/community-applications/#native (android released later this month)
2. additional specialised apps by the community: https://www.mattermost.org/community-applications/

**Comment by xmatthewx** [comment]
Ah, well, good to know. Case in point!

**Comment by xmatthewx** [comment]
Pages like https://github.com/mattermost/desktop/releases will scare many potential users. We should offer a shortlink in our invite email or a wiki help page. Or something. It'll be a pain to maintain the link to point to the latest, but easy setup is important.

**Comment by xmatthewx** [comment]
tracking in #49
