### ISSUE TITLE
Only allow authentication over https

### ISSUE THREAD

**Issue by TannerFilip** [mozilla/mattermoz#70]
Unless you specifically go to the https site, you're able to sign in/up over http. At a minimum, login pages should be served on https, but ideally the whole site would be.

**Comment by Pomax** [comment]
I didn't realize there wasn't a forced https connection at all - in addition to merely login, the goings-on in a chat service should never be unencrypted. I wonder if MatterMost itself does this, too.

**Comment by loganrosen** [comment]
Looks like this is fixed. Trying to access the site over http results in a redirect to https:

> $ curl -I chat.mozillafoundation.org
> HTTP/1.1 301 Moved Permanently
> Connection: keep-alive
> Server: nginx
> Date: Sat, 17 Sep 2016 02:57:31 GMT
> Content-Type: text/html
> Content-Length: 178
> Location: https://chat.mozillafoundation.org/
> Via: 1.1 vegur

**Comment by Pomax** [comment]
nice! marking as resolved in that case.
