### ISSUE TITLE
How can I contribute to this repository ?

### ISSUE THREAD

**Issue by dipakkr** [mozilla/mattermoz#91]
hi there, I am new in open source contribution and never contributed to any open source repo. I know java,git and currently learning android development.
Please help me get to started.

**Comment by Pomax** [comment]
Hi @dipakraj, this is the mozilla foundation's fork of the official MatterMost project so we can easily deploy it, so this particular repository doesn't really benefit from contributions since we simply sync it on what happens in the main MatterMost repository.

What kind of projects were you interest in working on? (And are you specifically looking for a Mozilla Foundation project, or a Mozilla project in general?)

**Comment by dipakkr** [comment]
Hi @Pomax,
Ya i know this is a fork of official MatterMost project. Actually i am looking for a open source project that is suitable for beginners and i found on web that Mozilla, Webmaker etc  is best for starting your journey with open source contribution, thats why i asked here.

It would be great if you suggest me some good project and resources to get started with open source contribution.It may be from Mozilla or other.
Thanks.

**Comment by Pomax** [comment]
the webmaker project is winding down right now; as far as I know the Foundation does not have any other java/android projects, but perhaps Firefox for Android might be interesting to you: you can find out more about joining that community over on https://wiki.mozilla.org/Mobile/Get_Involved - they have a list of good beginner/mentored bugs under the "Mentor Bugs" section that are good places to start, and they have their own IRC channel on irc.mozilla.org (the `#mobile` channel).

**Comment by dipakkr** [comment]
Thanks @Pomax for your suggestion, I will surely join the community and start contribiting

**Comment by ryanwarsaw** [comment]
Hi @dipakkr!

You might also be interested in Jisort (https://github.com/mozilla/Jisort). It's a prototype research app used by one of the Mozilla projects (Digital Skills Observatory). They're currently researching the impact of digital skills on people, smartphones, and digital financial services.

The goal of Jisort is to teach basic digital skills to first time smart phone users, or people who aren't proficient on the most basic digital skills. I'm currently leading the development of it, if this is something you'd be interested in contributing to you can contact me by email (ryanw@mozillafoundation.org), or reach out to me here on Github.

Learn more about DSO here: http://mozillafoundation.github.io/digital-skills-observatory/
